### ISSUE TITLE
Combatability with ARM on Pi4

### ISSUE THREAD

**Issue by LordBBQ** [Boomaa23/open-ds#18]
I am trying to setup a demo portable driver station by running OpenDS on a Pi4. I get the error 
`Exception in thread "main" com.boomaa.opends.util.NativeSystemError: Unsupported architecture aarch64
        at com.booma.opends.util.Architecture.getCurrent(Architecture.java:22)
        at com.booma.opends.util.Libraries.init(Libraries.java:22)
        at com.booma.opends.DisplayEndpoint.main(DisplayEndpoint.java:135)
`
Based on the error message it appears to be an issue with the ARM architecture.

**Comment by Boomaa23** [comment]
Hey, this looks like I just need to compile for Linux aarch64 and change some config. I'll get to it as soon as I can. Thanks!

**Comment by LordBBQ** [comment]
Great thanks!

**Comment by Boomaa23** [comment]
Hi @LordBBQ, you can try the below ZIP file (or compile yourself as of commit b3806092633d93c03c5c09748acd9c954a315096). Turns out there was a bit more to do but it should work now (I tested on my own rpi4). Please let me know if it does or does not work!

[open-ds-v0.2.4-SNAPSHOT-jar-with-dependencies.zip](https://github.com/Boomaa23/open-ds/files/9441601/open-ds-v0.2.4-SNAPSHOT-jar-with-dependencies.zip)

**Comment by LordBBQ** [comment]
Sorry for the delayed response, I finally got time to try it out. It runs ok, detects joystick, connects, enables, but the rsl flickers making me suspect it’s switching between enabled and disabled. Joystick cannot drive the robot and the PDP/PCM arn’t switching into enabled.

**Comment by Boomaa23** [comment]
Hmmm okay. I think I messed something up with some other unrelated changes I made. I'll troubleshoot this. In the meantime can you maybe try the JAR I sent you on another computer to see if that works?

**Comment by Boomaa23** [comment]
Hi again! I just tested with a Roborio and can't replicate your issue. Are you running a roborio 2?

**Comment by Boomaa23** [comment]
Hi there! I think I've fixed your issue. Please try this jar: [d49c019.jar](https://aptapus.net/opends/d49c019.jar).

 If that doesn't work, please try running with `java -jar (name of jar file) --debug` and show me the output. Also let me know if you're using a roborio 2 and if the new JAR works on any other computers you have.

**Comment by LordBBQ** [comment]
I’m running a RIO2. My team won’t meet again until build season so I can try and test it then. On 23 Dec 2022, at 4:51 pm, Boomaa23 ***@***.***> wrote:﻿
Hi there! I think I've fixed your issue. Please try this jar: d49c019.jar.
If that doesn't work, please try running with java -jar (name of jar file) --debug and show me the output. Also let me know if you're using a roborio 2 and if the new JAR works on any other computers you have.

**Comment by Boomaa23** [comment]
Hi, just wanted to bump this. If you are no longer having this problem, please close this issue.

**Comment by Boomaa23** [comment]
Hi @LordBBQ . Please let me know if you are still having this issue. If not, I will close it due to inactivity.
