### ISSUE TITLE
Error when starting on M1 Mac

### ISSUE THREAD

**Issue by team3572** [Boomaa23/open-ds#19]
java -version give me...
```
openjdk version "17.0.2" 2022-01-18 LTS
OpenJDK Runtime Environment Zulu17.32+13-CA (build 17.0.2+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.32+13-CA (build 17.0.2+8-LTS, mixed mode, sharing)
```

Running it...
`java -jar ./open-ds-v0.2.4.jar`

returns...
```
Exception in thread "main" com.boomaa.opends.util.NativeSystemError: Unsupported architecture aarch64
	at com.boomaa.opends.util.Architecture.getCurrent(Architecture.java:22)
	at com.boomaa.opends.util.Libraries.init(Libraries.java:18)
	at com.boomaa.opends.display.DisplayEndpoint.main(DisplayEndpoint.java:64)
```

**Comment by Boomaa23** [comment]
Hi, this has to do with a fix I made after v0.2.4, in commit https://github.com/Boomaa23/open-ds/commit/1638bb121c1a36452a3a04d82503e07c80cd5010. I can't do a release right now unfortunately as I am working on another major feature release. However if you download that commit and compile it you should be able to get it working.

**Comment by team3572** [comment]
OK, I did compile with that commit and got the program to run on my Mac.
The issue now is that  when I enable the Rio runs for a second or two then pauses then runs again for a second or two then pauses.
The amount of time running and the pause time are consistant.
It's like the DS is sending "teleop" or "test" packets for a fixed amount of time, then doesn't for a fixed amount of them then resumes, rinse and repeat.

This happened on LabView code that was deployed to the Rio, very simple code to run a single motor, and it also happened with a JAVA program I deployed as well. Again the most basic JAVA code that only ran a motor at 20% when test mode was enabled.

Let me know if you need any more info.

**Comment by Boomaa23** [comment]
Okay this sounds like a similar problem to #18. I will work on it when I can and follow up here.

**Comment by Boomaa23** [comment]
Hi there! I think I've fixed your issue. Please try this jar: [d49c019.jar](https://aptapus.net/opends/d49c019.jar).

If that doesn't work, please try running with java -jar (name of jar file) --debug and show me the output. Also let me know if you're using a roborio 2 and if the new JAR works on any other computers you have.

**Comment by Boomaa23** [comment]
Hi, just wanted to bump this. If you are no longer having this problem, please close this issue.

**Comment by titan2022-multiuser-system** [comment]
Hi, is d49c019.jar still the correct version to use for ARM64 macOS? Thanks!

**Comment by Boomaa23** [comment]
Hi, that should still work but you can use the latest build too: [a796a01.jar](https://opends.aptapus.net/builds/a796a01.jar)

**Comment by titan2022-multiuser-system** [comment]
Ok, thanks! I'll look into doing that.
