### ISSUE TITLE
Application fails to launch

### ISSUE THREAD

**Issue by willtoth** [Boomaa23/open-ds#5]
Trying to launch the application I get the following error:

```
william.toth@william ~ % java -jar Downloads/open-ds-v0.2.0.jar
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at com.boomaa.opends.usb.HIDDevice.<init>(HIDDevice.java:29)
	at com.boomaa.opends.usb.Joystick.<init>(Joystick.java:5)
	at com.boomaa.opends.usb.ControlDevices.instantiateHID(ControlDevices.java:49)
	at com.boomaa.opends.usb.ControlDevices.findAll(ControlDevices.java:33)
	at com.boomaa.opends.usb.ControlDevices.init(ControlDevices.java:18)
	at com.boomaa.opends.display.DisplayEndpoint.main(DisplayEndpoint.java:136)

```

This is with MacOS, using OpenJDK 11

**Comment by Boomaa23** [comment]
What USB devices do you have plugged in? I believe the error is an oversight on my part to assume all joystick-type devices are 3-axis but I want to make sure. Try [this JAR](https://ncocdn.cf/software/open-ds-v0.2.1-SNAPSHOT.jar) for now and let me know if it works.

**Comment by willtoth** [comment]
I'll give it a try. For reference I don't have anything plugged in via USB.

**Comment by Boomaa23** [comment]
Alright strange, I'll commit that fix. Thanks!
